name: bloc_library
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.14.0
  todos_app_core:
    path: ../todos_app_core
  todos_repository_simple:
    path: ../todos_repository_simple
  flutter:
    sdk: flutter

dependency_overrides:
  rxdart: ^0.22.0

dev_dependencies:
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

flutter:
  uses-material-design: true
